name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sample_app_1_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev
          bundle install

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/sample_app_1_test
        run: |
          bundle exec rails db:drop DISABLE_DATABASE_ENVIRONMENT_CHECK=1 || true
          bundle exec rails db:create
          bundle exec rails db:schema:load


      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/sample_app_1_test
        run: |
          echo "Running tests in env: $RAILS_ENV"
          bundle exec rails db:migrate
          bundle exec rails test

      - name: Run security checks
        run: |
          bundle exec brakeman -q -w2

      - name: Run linting
        run: |
          bundle exec rubocop
